### ISSUE TITLE
support SCP

### ISSUE THREAD

**Issue by bhcleek** [bhcleek/packer-provisioner-ansible#4]
Ansible uses SCP to copy files by setting `scp_if_ssh=True` http://docs.ansible.com/intro_configuration.html#scp-if-ssh`

**Comment by kwilczynski** [comment]
@bhcleek sorry to bother you, but did you ever got around to tackling scp? I am having a similar problem to solve (namely, the lack of scp support), and was thinking about how to tackle this to add it to the provisioner. I've seen this: https://blogs.oracle.com/janp/entry/how_the_scp_protocol_works; and I've been working how to add it to the SSH proxy. What's your opinion?

**Comment by bhcleek** [comment]
I haven't tackled it yet. The article you linked to is a great starting point; it's what I've used to research what would need to be done. 

Packer has SCP functionality built into the [ssh communicator] (https://github.com/mitchellh/packer/tree/master/communicator/ssh/communicator.go). You could also use that as a reference to understand what a client (e.g Ansible) will send to the server.

**Comment by kwilczynski** [comment]
Thank you for getting back to me! I did had a look :) It seem that it would send *exec* request on the channel with something along the lines of `ssh -t /tmp/some/path`, which could be dealt with. The thing I am not sure, is how to make this happen via the SSH proxy yet (needs figuring out), so that it lunches exact command on the remote side and then allows for data to pass through it (especially the confirmations `\x0`) back and forward.

**Comment by bhcleek** [comment]
This has been implemented in the official provisioner within packer.
