### ISSUE TITLE
 DRY the code

### ISSUE THREAD

**Issue by jan-xyz** [bhcleek/packer-provisioner-ansible#8]
Hi I had a look at your code for different reasons and it isn't maintained by anyone at the moment, if I see that correctly.

Is there any particular reason, for example, why you implemented your own ssh adapter and aren't using the communicator provided by packer? I guess removing the adapter and going to the standard implementation would remove a huge barrier for people to get involved.

I started to DRY the code and combine a lot of things with the local provisioner and started implementing multistep. However, the adapter was the bit where I actually stumbled and stopped, primarily, because I don't understand what's happening there.

**Comment by bhcleek** [comment]
The provisioner has been integrated into Packer; if you want to contribute, you should do it there.

The provisioner has an SSH adapter, because the communication with the node is abstracted by packer with the Communicator interface, which only has a few methods. The communicator is not necessarily speaking SSH to the node; there are also communicators for WinRM and Docker. 

Ansible also uses multiple communication methods (SSH, WinRM, and Docker, too!) But Packer doesn't expose any details to the provisioners about which communication method is being used, so there's no way to create an inventory file for Ansible that will tell Ansible the details that it needs for its connection to the node.

So this provisioner creates an SSH adapter so that Ansible can communicate via SSH, and the adapter takes care of translating the SSH requests into communicator methods.

**Comment by PinguinXY** [comment]
Thank you for your reply, that cleared up a lot for me. I am well aware that this fork isn't where I should contribute, I actually wanted to write a message to you, but I couldn't find the button for that.

Does it make sense to put that burden to the user though? If it doesn't work because he chose two conflicting connection methods, it's his fault. At least for a start. For the future I think it makes sense to implement a similar way of handling stuff as packer is already [implementing it for builders](https://www.packer.io/docs/templates/provisioners.html):
```
{
  "type": "shell",
  "script": "script.sh",
  "only": ["virtualbox-iso"]
}
```
That way the user can have different configurations depending on the communicator in one config file. And maybe, at some point the type of communicator is even handed down to the provisioner so it can check dynamically which method it should use.

That would mean for now:
* add a configuration field for the [ansible_connection](http://docs.ansible.com/ansible/intro_windows.html#inventory)
* replace custom adapter with packer communicator

If the field is left blank it will default to ssh, that way it won't break anything with already existing configurations.

**Comment by PinguinXY** [comment]
I just read [your comment](https://github.com/mitchellh/packer/issues/3260#issuecomment-194928281), that the ssh connection is only used to have a communication medium between packer and ansible.

That makes my stuff above obsolete.

If I understand that correctly now: 
* You have a connection to the node via whatever packer is using and whatever the user is configuring.
* You have an ssh connection between Ansible (on the host) and packer (also on the host) so that you can display the output from ansible?

**Comment by bhcleek** [comment]
That's right.
